In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# data = pd.read_csv("./perceptron_data.csv")

In [3]:
# Generate data
import itertools
n = 3
lst = list(itertools.product([0, 1], repeat=n))
data = pd.DataFrame(lst)

In [4]:
data

0  1  2
0  0  0  0
1  0  0  1
2  0  1  0
3  0  1  1
4  1  0  0
5  1  0  1
6  1  1  0
7  1  1  1

In [5]:
first_half = np.zeros(int(len(data)/2)).astype(int)
# first_half

In [6]:
second_half = np.ones(int(len(data)/2)).astype(int)
# second_half

In [7]:
output = np.hstack((first_half, second_half))

In [8]:
# output

In [9]:
data['output'] = output

In [10]:
data

0  1  2  output
0  0  0  0       0
1  0  0  1       0
2  0  1  0       0
3  0  1  1       0
4  1  0  0       1
5  1  0  1       1
6  1  1  0       1
7  1  1  1       1

In [11]:
# i=1
# idx = []

# while(i<len(data)):
#     idx.append(i)
#     i = i+2
    
# data.drop(idx,axis=0, inplace=True)

# data = data.reset_index(drop=True)

In [12]:
# data = data.reset_index(drop=True)

In [13]:
X = data.iloc[:, 1:data.shape[1]].values

In [14]:
X.shape

(8, 3)

In [15]:
y = data.iloc[:, -1].values

In [16]:
desired = y

In [17]:
y.shape

(8,)

In [18]:
desired.shape

(8,)

# Train Test Split

In [19]:
train_percentage = 0.8;
row = int(data.shape[0]*train_percentage)

In [20]:
data.shape[1]

4

In [21]:
X_train = data.iloc[:row, 1:data.shape[1]].values

In [22]:
X_test = data.iloc[row: ,1:data.shape[1]].values

In [23]:
X_train.shape

(6, 3)

In [24]:
X_test.shape

(2, 3)

In [25]:
y_train = data.iloc[ :row,-1].values

In [26]:
y_train.shape

(6,)

In [27]:
y_test = data.iloc[ row:,-1].values

In [28]:
y_test.shape

(2,)

# Single Layer Perceptron

In [67]:
def summation(W,X):
#     print(type(W))
#     print(type(X))
    result = 0
    for i in range(len(W)):
        result += W[i]*X[i]

    return result

In [56]:
# np.random.random()
def step(z):
    if z>= 0.5:
        return 1
    else:
        return 0

In [57]:
def perceptron(X,y):
    weights = np.array([0.1, 0.3, 0.2])
    prev_weight = weights
    
    lr = 1
    
    while(True):
        for j in range(len(X)):
            actual = step(summation(weights,X[j]))
            weights = weights + lr*(desired[j]-actual)*X[j]
            
        if(np.array_equal(weights,prev_weight)):
            break
            
        prev_weight = weights
        
    return weights

In [58]:
adapt_weight = perceptron(X_train,y_train)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [33]:
print(adapt_weight)

[0.1 0.3 1.2]


# Accuracy

In [34]:
# create a list to store the predictions
y_pred = []

In [35]:
# loop over the test data
for test_data in X_test:
    # predict the label for the test point
    label = step(summation(adapt_weight,test_data))
    y_pred.append(label)

In [36]:
y_pred

[1, 1]

In [37]:
y_test

array([1, 1])

In [38]:
# calculate the accuracy of the classifier
accuracy = sum(y_pred == y_test) / len(y_test)
print("Accuracy: ", accuracy*100, "%")

Accuracy:  100.0 %


# Input Test Data

In [49]:
# x1 =int(input("Enter x1:"))
# x2 =int(input("Enter x2:"))
# x3 =int(input("Enter x3:"))
x1 = 1 
x2 = 0
x3 = 1

In [59]:
test_data = [x1,x2,x3]

In [60]:
type(test_data)

list

In [61]:
test_data = np.array(test_data)

In [63]:
test_data

array([1, 0, 1])

In [65]:
adapt_weight

array([0.1, 0.3, 1.2])

In [70]:
Sum = summation(adapt_weight,test_data)

In [71]:
result = step(Sum)

In [72]:
if result == 0:
    print("Output 0")
else:
    print("Output 1")

1