In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# data = pd.read_csv("./perceptron_data.csv")

In [3]:
# Generate data
import itertools
n = 3
lst = list(itertools.product([0, 1], repeat=n))
data = pd.DataFrame(lst)

In [4]:
data

0  1  2
0  0  0  0
1  0  0  1
2  0  1  0
3  0  1  1
4  1  0  0
5  1  0  1
6  1  1  0
7  1  1  1

In [5]:
first_half = np.zeros(int(len(data)/2)).astype(int)
# first_half

In [6]:
second_half = np.ones(int(len(data)/2)).astype(int)
# second_half

In [7]:
output = np.hstack((first_half, second_half))

In [8]:
data['output'] = output

In [9]:
data

0  1  2  output
0  0  0  0       0
1  0  0  1       0
2  0  1  0       0
3  0  1  1       0
4  1  0  0       1
5  1  0  1       1
6  1  1  0       1
7  1  1  1       1

# Groupwise separate data

In [10]:
def groupData(val):
    mask = data['output']==val
    return data[mask]

In [11]:
group_0 = groupData(0)

In [12]:
group_0

0  1  2  output
0  0  0  0       0
1  0  0  1       0
2  0  1  0       0
3  0  1  1       0

In [13]:
group_1 = groupData(1)

In [14]:
group_1

0  1  2  output
4  1  0  0       1
5  1  0  1       1
6  1  1  0       1
7  1  1  1       1

# Train Test Split

In [15]:
train_percentage = .8;
row = int(group_0.shape[0]*train_percentage)

In [16]:
row

2

In [17]:
X_train_0 = group_0.iloc[:row, :group_0.shape[1]-1]
X_train_1 = group_1.iloc[:row, :group_0.shape[1]-1]

In [18]:
# X_train_0

In [19]:
# X_train_1

In [20]:
frames = [X_train_0, X_train_1]
X_train = pd.concat(frames)

In [21]:
X_train = X_train.values

In [22]:
# X_train

In [23]:
X_test_0 = group_0.iloc[row: , :group_0.shape[1]-1]
X_test_1 = group_1.iloc[row: , :group_1.shape[1]-1]

In [24]:
# X_test_0

In [25]:
# X_test_1

In [26]:
frames = [X_test_0, X_test_1]
X_test = pd.concat(frames)

In [27]:
X_test = X_test.values

In [28]:
# X_test

In [29]:
# X_train.shape

In [30]:
# X_test.shape

In [31]:
y_train_0 = group_0.iloc[ :row,-1]
y_train_1 = group_1.iloc[ :row,-1]

In [32]:
frames = [y_train_0, y_train_1]
y_train = pd.concat(frames)

In [33]:
y_train = y_train.values

In [34]:
# y_train

In [35]:
# y_train.shape

In [36]:
y_test_0 = group_0.iloc[ row:,-1]
y_test_1 = group_1.iloc[ row:,-1]

In [37]:
frames = [y_test_0, y_test_1]
y_test = pd.concat(frames)

In [38]:
y_test = y_test.values

In [39]:
# y_test.shape

In [40]:
# y_test

# Single Layer Perceptron

In [41]:
def summation(W,X):
#     print(type(W))
#     print(type(X))
    result = 0
    for i in range(len(W)):
        result += W[i]*X[i]

    return result

In [42]:
# np.random.random()
def step(z):
    if z> 0.5:
        return 1
    else:
        return 0

In [43]:
def perceptron(X,y, weights):
    prev_weight = weights
    lr = 1
    
    while(True):
        for i in range(len(X)):
            actual = step(summation(weights,X[i]))
            weights = weights + lr*(y[i]-actual)*X[i]
            #if don't match, then go back to first iteration and repeat the process
            if(actual != y[i]):
                break
                
            
        if(np.array_equal(weights,prev_weight)):
            break
            
        prev_weight = weights
        
    return weights

In [44]:
weights = np.array([0.1, 0.3, 0.2])

In [45]:
# X_train[:2]

In [46]:
# y_train[:2]

In [47]:
# X_train[2:]

In [48]:
# y_train[2:]

In [49]:
# group_0_weight = perceptron(X_train[:row],y_train[:row], weights)

In [50]:
# group_0_weight

In [51]:
# group_1_weight = perceptron(X_train[row:],y_train[row:], weights)

In [52]:
# group_1_weight

In [53]:
while(True):
    group_0_weight = perceptron(X_train[:row],y_train[:row], weights)
    group_1_weight = perceptron(X_train[row:],y_train[row:], weights)
    
    if(np.array_equal(group_0_weight,group_1_weight)):
        break
        
    weights = group_1_weight

In [54]:
adapt_weight = weights

# Accuracy

In [55]:
# create a list to store the predictions
y_pred = []

In [56]:
# loop over the test data
for test_data in X_test:
    # predict the label for the test point
    label = step(summation(adapt_weight,test_data))
    y_pred.append(label)

In [57]:
y_pred = np.array(y_pred)

In [58]:
y_pred

array([0, 0, 1, 1])

In [59]:
y_test

array([0, 0, 1, 1])

In [60]:
# calculate the accuracy of the classifier
accuracy = sum(y_pred == y_test) / len(y_test)
print("Accuracy: ", accuracy*100, "%")

Accuracy:  100.0 %


# Input Test Data

In [61]:
# x1 =int(input("Enter x1:"))
# x2 =int(input("Enter x2:"))
# x3 =int(input("Enter x3:"))
x1 = 1 
x2 = 0
x3 = 1

In [62]:
test_data = [x1,x2,x3]

In [63]:
type(test_data)

list

In [64]:
test_data = np.array(test_data)

In [65]:
test_data

array([1, 0, 1])

In [66]:
# adapt_weight

In [67]:
Sum = summation(adapt_weight,test_data)

In [68]:
result = step(Sum)

In [69]:
if result == 0:
    print("Output 0")
else:
    print("Output 1")

Output 1
