In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
o_ai = np.random.uniform(0,1,2)
t_ak = np.random.uniform(0,1,2)
u = np.random.uniform(0,1,2)

# o_ai = np.array([0.05, 0.10])
# t_ak = np.array([0.01, 0.99])
# u = np.array([0.35, 0.60])  #threshold or bias

In [3]:
w_ij = np.random.uniform(0,1,4).reshape(2,2)

# w_ij = np.array([[0.15, 0.25],[0.20, 0.30]])

In [4]:
w_ij

array([[0.15, 0.25],
       [0.2 , 0.3 ]])

In [5]:
w_jk = np.random.uniform(0,1,4).reshape(2,2)
# w_jk = np.array([[0.40, 0.50],[0.45, 0.55]])

In [6]:
w_jk

array([[0.4 , 0.5 ],
       [0.45, 0.55]])

In [7]:
n1 = np.random.random()
k1 = np.random.random()
n2 = np.random.random()
k2 = np.random.random()

# n1 = 1
# k1 = 1
# n2 = 1
# k2=1

In [8]:
# w_jk[1][0]

In [9]:
def summation(W,X):
    result = []
    for i in range(len(X)):
        SUM = 0
        for j in range(W.shape[0]):
            SUM += W[j][i]*X[j]
            
        result.append(SUM)
        
        
    return result

In [10]:
def SUM(del_a,w):
#     print(w.shape[0])
    result = []
    for i in range(len(del_a)):
        SUM = 0
        for j in range(w.shape[0]):
            SUM += del_a[j]*w[i][j]
            
        result.append(SUM)
        
        
    return result

In [11]:
def sigmoid(x):
    return 1 / (1 + np.exp(-k1*x))


In [12]:
Min_Error = 0.005

while(True):
    # EQUATION 1
    net_aj = summation(w_ij, o_ai)
    
    # EQUATION 2
    u_hj = u[0]
    activ_j = net_aj + u_hj
    
    # EQUATION 3
    o_aj = sigmoid(activ_j)
    
    # EQUATION 4
    net_ak = summation(w_jk, o_aj)
    
    # EQUATION 5
    u_ok = u[1]
    activo_k = net_ak + u_ok
    
    # EQUATION 6
    o_ak = sigmoid(activo_k)
    
    # EQUATION 7
    del_ak = t_ak - o_ak
    
     # EQUATION 16
    Error = 0.5*sum(np.power((t_ak-o_ak),2))
    print(Error)
    
    if(Error <= Min_Error):
        break
    
    # EQUATION 8
    del_w_jk = n2*k2*del_ak*o_aj*o_ak*(1-o_ak)
    
    # EQUATION 9
    w_jk = w_jk + del_w_jk
    
    # EQUATION 10
    del_u_ok = n2*k2*del_ak*o_ak*(1-o_ak)
    
    # EQUATION 11
    u_ok = u_ok + del_u_ok
    
    # EQUATION 12
    del_w_ij = n2*k2*o_ai*o_aj*(1-o_aj)*SUM(del_ak,w_jk)
    
    # EQUATION 13
    w_ij = w_ij + del_w_ij
    
    # EQUATION 14
    del_u_hj = n1*k1*o_aj*(1-o_aj)*SUM(del_ak,w_jk)
    
    # EQUATION 15
    u_hj = u_hj + del_u_hj
    
   

0.2983711087600027
0.2836545113747834
0.2684442707050492
0.25287022678156595
0.23709641716632676
0.2213134561430947
0.2057264884289774
0.19054009326459653
0.17594250388959912
0.16209188570781513
0.14910696016352573
0.13706312595161735
0.12599387718571078
0.1158962546465324
0.10673858013004695
0.09846880447868728
0.09102223480409258
0.0843279438018403
0.07831362550889655
0.0729089721571955
0.06804780799624183
0.06366926679404747
0.059718284794992055
0.05614563564682926
0.05290768085852349
0.049965960627511366
0.04728671012284694
0.044840356248378475
0.04260102838912106
0.040546101906172756
0.03865578345242824
0.03691274106889894
0.03530177835870773
0.033809549996030974
0.03242431482923452
0.031135722484903414
0.029934629409109757
0.028812940523430697
0.027763473018142207
0.026779839187701576
0.02585634559538869
0.024987906213503955
0.024169967512413324
0.023398443762165357
0.022669661064422014
0.021980308852173357
0.021327397783303653
0.020708223115069424
0.020120332783456735
0.01956149

In [13]:
w_ij

array([[0.73371873, 1.38828193],
       [0.78371873, 1.43828193]])

In [14]:
w_jk

array([[-2.39827661,  1.50206005],
       [-2.34827661,  1.55206005]])

In [15]:
# # EQUATION 1
# net_aj = summation(w_ij, o_ai)

In [16]:
# net_aj

In [17]:
# # EQUATION 2
# u_hj = u[0]
# activ_j = net_aj + u_hj

In [18]:
# # EQUATION 3
# o_aj = sigmoid(activ_j)

In [19]:
# o_aj

In [20]:
# # EQUATION 4
# net_ak = summation(w_jk, o_aj)

In [21]:
# # EQUATION 5
# u_ok = u[1]
# activo_k = net_ak + u_ok

In [22]:
# # EQUATION 6
# o_ak = sigmoid(activo_k)

In [23]:
# o_ak

In [24]:
# # EQUATION 7
# del_ak = t_ak - o_ak

In [25]:
# del_ak

In [26]:
# # EQUATION 8
# n2=1
# k2=1
# del_w_jk = n2*k2*del_ak*o_aj*o_ak*(1-o_ak)

In [27]:
# # EQUATION 9
# w_jk = w_jk + del_w_jk

In [28]:
# w_jk

In [29]:
# # EQUATION 10
# del_u_ok = n2*k2*del_ak*o_ak*(1-o_ak)

In [30]:
# del_u_ok

In [31]:
# # EQUATION 11
# u_ok = u_ok + del_u_ok

In [32]:
# u_ok

In [33]:
# del_ak

In [34]:
# w_jk

In [35]:
# result = SUM(del_ak,w_jk)

In [36]:
# result

In [37]:
# # EQUATION 12
# n1=1
# k1=1
# del_w_ij = n2*k2*o_ai*o_aj*(1-o_aj)*SUM(del_ak,w_jk)

In [38]:
# del_w_ij

In [39]:
# # EQUATION 13
# w_ij = w_ij + del_w_ij

In [40]:
# # EQUATION 14
# n1=1
# k1=1
# del_u_hj = n1*k1*o_aj*(1-o_aj)*SUM(del_ak,w_jk)

In [41]:
# # EQUATION 15
# u_hj = u_hj + del_u_hj

In [42]:
# t_ak

In [43]:
# o_ak

In [44]:
# sum((t_ak-o_ak)*(t_ak-o_ak))

In [45]:
# # EQUATION 16
# Error = 0.5*sum((t_ak-o_ak)*(t_ak-o_ak))

In [46]:
# Error

In [47]:
# sum(np.power((t_ak-o_ak),2))